# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    concurrency: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}/plan

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "# OK" >> $GITHUB_SUMMARY

  # This workflow contains a single job called "build"
  apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    concurrency: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!!!
