name: Retry

on:
  workflow_run:
    workflows:
      - "CI"
    types: ["completed"]

jobs:
  retry:
    runs-on: ubuntu-latest
    # if: >-
    #   github.event.workflow_run.conclusion == 'failure'
    if: >-
      github.event.workflow_run.run_attempt < 3
    steps:
      - name: 'Retry Workflow'
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context.payload);
            await github.request(`POST ${context.payload.workflow_run.rerun_url}`);
