name: Split PR

on:
  issue_comment:
    types: [created]

jobs:
  split-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/split-pr') }}

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        uses: mitene/split-pr@main
        with:
          pull-number: ${{ github.event.issue.number }}
          file-pattern: "dir/**"
          branch-suffix: "-split"
          commit-message: "Split PR #${{ github.event.issue.number }}"
          commit-user: ${{ github.event.sender.login }}
          commit-email: ${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com
          title-prefix: "split-pr: "
          token: ${{ github.token }}
